Add missing msg attr_reader method
`@msg` is important because it's the only way to the error details for, eg, an `AuthenticationError`:

```ruby
[21] pry(main)> e
=> #<Adyen::PermissionError: Adyen::PermissionError>
[22] pry(main)> e.code
=> 403
[23] pry(main)> e.response
=> nil
[24] pry(main)> e.msg
NoMethodError: undefined method `msg' for #<Adyen::PermissionError: Adyen::PermissionError>
from (pry):24:in `rescue in <main>'
[25] pry(main)> e.instance_variable_get('@msg')
=> "Invalid Checkout API key"
```